### ISSUE TITLE
`idToken` from localstorage being `"undefined"`

### ISSUE THREAD

**Issue by namiwang** [johnlim/auth0-element#1]
In `auth0-auth`:
```
        // Get the user token if we've saved it in localStorage before
        var idToken = localStorage.getItem(this.localStorageKey); // <- HERE
        if (idToken) {
          // If there's a token, just redirect to "targetUrl" if any
          //window.location.href = '#/leave-types';
          this._getProfile(idToken);
          return;
        }
```

In the snippet above, the value of var `idToken` taken out from localStorage is `"undefined"`, instead of `undefined`, thus cause some critical error in `_getProfile`.

Tried more in console about localstorage:
```
> localStorage
> Storage {auth0:authUser: "undefined", length: 1}
> localStorage.foo
> null
```

I've not dig more, though glad to help if you need more info.

Thx for the component!

**Comment by johnlim** [comment]
@nanowang Hmm, this is indeed strange. The key `auth0:authUser` should not exist till authentication is successful. How are you using the element? This is how I use the element 
```   
 <auth0-auth
      id="auth0"
      client-id="{{auth0.clientId}}"
      domain="{{auth0.domain}}"
      options="{{auth0.options}}"
      logout-redirect-to="{{auth0.logoutRedirectTo}}"
      user-profile={{user}}
      id-token="{{idToken}}"
      hosted-pages>
    </auth0-auth>
```
 Where hosted-pages is optional else it'll use the auth0 lock widget. If you could provide more details on how to replicate the issue, I'll be more than happy to take a look.  You could also try clearing the localStorage and reloading the app but Im guessing that doesn't solve the problem.

**Comment by namiwang** [comment]
Strange indeed. I'll go dig in a little more. BTW I'm using polymer 2.0-preview, is that compatible?

**Comment by johnlim** [comment]
@nanowang I've just tested the component with polymer 2.0-preview and am also experiencing the issue you mentioned. Unfortunately, the `auth0-element` component has not been ported to 2.0 yet.

**Comment by namiwang** [comment]
@johnlim 

As said in https://www.polymer-project.org/2.0/docs/about_20#observer-changes

```
Observer changes

In 2.0, the checks preventing observers from firing with undefined dependencies are removed.

Specifically:

- Multi-property observers and computed properties run once at initialization if any dependencies are defined.
```

I guess this, and the observer `_setLocalStorage(localStorageKey, idToken)` together cause the issue.

**Comment by johnlim** [comment]
@nanowang thanks for looking into it. I do plan to port it to Polymer 2.0 once theres more clarity from the Polymer team. Would you mind if I closed this and we can re-open it when Polymer 2.0 is officially released?

**Comment by namiwang** [comment]
Sure thing

**Comment by johnlim** [comment]
@nanowang I've ported the element to Polymer 2.0. You may find it in the branch `2.0-preview`. The component has also been upgraded to use auth0.js V8. However, auth0-delegate is broken at the moment but it'll be fixed as soon as I get a response from Auth0 support. Documentation is still lacking so please let me know if you need any help in using the element.

**Comment by namiwang** [comment]
@johnlim Awesome! Thanks for your time!
